version: "2"

linters:
  disable:
    - typecheck # Disable problematic typecheck
  enable:
    - gofmt
    - govet
    - ineffassign
    - misspell
    - unconvert
    - unused

run:
  timeout: 5m
  modules-download-mode: readonly
