// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import (
	"embed"

	"github.com/swaggo/swag"
)

//go:embed swagger_template.json
var templateFS embed.FS

func getDocTemplate() string {
	content, err := templateFS.ReadFile("swagger_template.json")
	if err != nil {
		// Fallback to empty template if file cannot be read
		return "{}"
	}
	return string(content)
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:30081",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Raqeem Mentor Backend API",
	Description:      "Device management and monitoring dashboard API for Raqeem IoT platform\nProvides endpoints for device listing, metrics retrieval, alert management, and remote command execution",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  getDocTemplate(),
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
