apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    app: postgres
    platform: raqeem
spec:
  containers:
    - name: postgres-container
      image: postgres:13
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_USER
          value: "monitor"
        - name: POSTGRES_PASSWORD
          value: "supersecret"
        - name: POSTGRES_DB
          value: "monitoring_db"
      resources:
        requests:
          cpu: "250m"
          memory: "256Mi"
        limits:
          cpu: "500m"
          memory: "512Mi"
      volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
  volumes:
    - name: postgres-storage
      persistentVolumeClaim:
        claimName: postgres-pvc
