apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  labels:
    platform: raqeem
spec:
  selector:
    app: postgres
    platform: raqeem
  type: ClusterIP
  ports:
    - name: postgres-port
      port: 5432
      targetPort: 5432
      protocol: TCP
---

